server:
  port: 9080

spring:
  application:
    name: kd-cloud-business-demo
  profiles:
      active: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://kedong:123456@localhost:1001/eureka

---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://kedong:123456@localhost:1001/eureka
---
spring:
  profiles: prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://kedong:123456@localhost:1001/eureka

